import type { Question, Topic } from "./types";

// Questões curtas, 1 passo, resolvíveis em ~15s.
export const QUESTIONS: Record<Topic, Question[]> = {
  exp: [
    {
      id: "exp-1",
      topic: "exp",
      prompt: "Quanto vale 2⁵?",
      options: ["16", "25", "32", "64"],
      correct: 2,
      formula: "2⁵ = 2·2·2·2·2",
      explanation: "2⁵ = 32.",
    },
    {
      id: "exp-2",
      topic: "exp",
      prompt: "Quanto vale 3³?",
      options: ["9", "18", "27", "81"],
      correct: 2,
      formula: "aⁿ = a · a · ... (n vezes)",
      explanation: "3³ = 3·3·3 = 27.",
    },
    {
      id: "exp-3",
      topic: "exp",
      prompt: "Quanto vale 2⁸?",
      options: ["128", "256", "512", "1024"],
      correct: 1,
      formula: "2⁸ = 256",
      explanation: "2⁸ = 256. (Dica: 2¹⁰ = 1024)",
    },
    {
      id: "exp-4",
      topic: "exp",
      prompt: "Quanto vale 5²?",
      options: ["10", "20", "25", "50"],
      correct: 2,
      formula: "a² = a · a",
      explanation: "5² = 5·5 = 25.",
    },
    {
      id: "exp-5",
      topic: "exp",
      prompt: "Se 2ˣ = 16, quanto vale x?",
      options: ["2", "3", "4", "5"],
      correct: 2,
      formula: "2ˣ = b ⇒ x = log₂(b)",
      explanation: "2⁴ = 16, então x = 4.",
    },
    {
      id: "exp-6",
      topic: "exp",
      prompt: "Quanto vale 2⁶?",
      options: ["32", "48", "64", "128"],
      correct: 2,
      formula: "2⁶ = 64",
      explanation: "2⁶ = 64.",
    },
    {
      id: "exp-7",
      topic: "exp",
      prompt: "Se 3ˣ = 27, quanto vale x?",
      options: ["2", "3", "4", "9"],
      correct: 1,
      formula: "aˣ = b",
      explanation: "3³ = 27, logo x = 3.",
    },
    {
      id: "exp-8",
      topic: "exp",
      prompt: "Quanto vale 2⁷?",
      options: ["64", "96", "128", "256"],
      correct: 2,
      formula: "2⁷ = 128",
      explanation: "2⁷ = 128.",
    },
  ],
  log: [
    {
      id: "log-1",
      topic: "log",
      prompt: "log₂(8) = ?",
      options: ["2", "3", "4", "8"],
      correct: 1,
      formula: "log_a(b) = x ⇔ aˣ = b",
      explanation: "2³ = 8, então log₂(8) = 3.",
    },
    {
      id: "log-2",
      topic: "log",
      prompt: "log₂(16) = ?",
      options: ["2", "3", "4", "8"],
      correct: 2,
      formula: "log_a(b) = x ⇔ aˣ = b",
      explanation: "2⁴ = 16, então log₂(16) = 4.",
    },
    {
      id: "log-3",
      topic: "log",
      prompt: "log₂(32) = ?",
      options: ["4", "5", "6", "8"],
      correct: 1,
      formula: "log_a(b) = x ⇔ aˣ = b",
      explanation: "2⁵ = 32, então log₂(32) = 5.",
    },
    {
      id: "log-4",
      topic: "log",
      prompt: "log₃(9) = ?",
      options: ["1", "2", "3", "9"],
      correct: 1,
      formula: "log_a(b) = x ⇔ aˣ = b",
      explanation: "3² = 9, então log₃(9) = 2.",
    },
    {
      id: "log-5",
      topic: "log",
      prompt: "log₁₀(100) = ?",
      options: ["1", "2", "10", "100"],
      correct: 1,
      formula: "log_a(b) = x ⇔ aˣ = b",
      explanation: "10² = 100, então log₁₀(100) = 2.",
    },
    {
      id: "log-6",
      topic: "log",
      prompt: "log₂(64) = ?",
      options: ["5", "6", "7", "8"],
      correct: 1,
      formula: "log_a(b) = x ⇔ aˣ = b",
      explanation: "2⁶ = 64, então log₂(64) = 6.",
    },
    {
      id: "log-7",
      topic: "log",
      prompt: "log₅(25) = ?",
      options: ["1", "2", "5", "25"],
      correct: 1,
      formula: "log_a(b) = x ⇔ aˣ = b",
      explanation: "5² = 25, então log₅(25) = 2.",
    },
    {
      id: "log-8",
      topic: "log",
      prompt: "log₂(4) = ?",
      options: ["1", "2", "3", "4"],
      correct: 1,
      formula: "log_a(b) = x ⇔ aˣ = b",
      explanation: "2² = 4, então log₂(4) = 2.",
    },
  ],
  pa: [
    {
      id: "pa-1",
      topic: "pa",
      prompt: "PA: 2, 5, 8, 11, ... Qual a razão?",
      options: ["2", "3", "4", "5"],
      correct: 1,
      formula: "r = a₂ − a₁",
      explanation: "5 − 2 = 3. A razão é 3.",
    },
    {
      id: "pa-2",
      topic: "pa",
      prompt: "PA com a₁=1 e r=4. Qual é a₅?",
      options: ["13", "16", "17", "20"],
      correct: 2,
      formula: "aₙ = a₁ + (n−1)·r",
      explanation: "a₅ = 1 + 4·4 = 17.",
    },
    {
      id: "pa-3",
      topic: "pa",
      prompt: "PA: 10, 13, 16, 19, ... Qual é o 5º termo?",
      options: ["20", "21", "22", "25"],
      correct: 2,
      formula: "aₙ = a₁ + (n−1)·r",
      explanation: "r = 3; a₅ = 10 + 4·3 = 22.",
    },
    {
      id: "pa-4",
      topic: "pa",
      prompt: "PA com a₁=3 e r=5. Qual é a₄?",
      options: ["15", "18", "20", "23"],
      correct: 1,
      formula: "aₙ = a₁ + (n−1)·r",
      explanation: "a₄ = 3 + 3·5 = 18.",
    },
    {
      id: "pa-5",
      topic: "pa",
      prompt: "PA: 4, 7, 10, ... Qual é o 6º termo?",
      options: ["16", "19", "21", "22"],
      correct: 1,
      formula: "aₙ = a₁ + (n−1)·r",
      explanation: "r = 3; a₆ = 4 + 5·3 = 19.",
    },
    {
      id: "pa-6",
      topic: "pa",
      prompt: "Firewall cresce 10, 15, 20, 25, ... Qual no 6º turno?",
      options: ["30", "35", "40", "45"],
      correct: 1,
      formula: "aₙ = a₁ + (n−1)·r",
      explanation: "r = 5; a₆ = 10 + 5·5 = 35.",
    },
    {
      id: "pa-7",
      topic: "pa",
      prompt: "Soma da PA: 2, 4, 6, 8, 10.",
      options: ["20", "25", "30", "40"],
      correct: 2,
      formula: "Sₙ = (a₁ + aₙ) · n / 2",
      explanation: "S = (2+10)·5/2 = 30.",
    },
    {
      id: "pa-8",
      topic: "pa",
      prompt: "PA: 5, 8, 11, ... Qual é o 4º termo?",
      options: ["12", "13", "14", "15"],
      correct: 2,
      formula: "aₙ = a₁ + (n−1)·r",
      explanation: "r = 3; a₄ = 5 + 3·3 = 14.",
    },
  ],
  pg: [
    {
      id: "pg-1",
      topic: "pg",
      prompt: "PG: 2, 4, 8, 16, ... Qual a razão?",
      options: ["1", "2", "3", "4"],
      correct: 1,
      formula: "q = a₂ / a₁",
      explanation: "4 / 2 = 2. A razão é 2.",
    },
    {
      id: "pg-2",
      topic: "pg",
      prompt: "PG com a₁=1 e q=2. Qual é a₅?",
      options: ["8", "10", "16", "32"],
      correct: 2,
      formula: "aₙ = a₁ · qⁿ⁻¹",
      explanation: "a₅ = 1·2⁴ = 16.",
    },
    {
      id: "pg-3",
      topic: "pg",
      prompt: "PG: 3, 6, 12, 24, ... Qual o 5º termo?",
      options: ["36", "48", "50", "96"],
      correct: 1,
      formula: "aₙ = a₁ · qⁿ⁻¹",
      explanation: "q = 2; a₅ = 3·2⁴ = 48.",
    },
    {
      id: "pg-4",
      topic: "pg",
      prompt: "PG com a₁=2 e q=3. Qual é a₃?",
      options: ["12", "15", "18", "24"],
      correct: 2,
      formula: "aₙ = a₁ · qⁿ⁻¹",
      explanation: "a₃ = 2·3² = 18.",
    },
    {
      id: "pg-5",
      topic: "pg",
      prompt: "PG: 1, 3, 9, 27, ... Qual o 5º termo?",
      options: ["54", "81", "90", "108"],
      correct: 1,
      formula: "aₙ = a₁ · qⁿ⁻¹",
      explanation: "q = 3; a₅ = 1·3⁴ = 81.",
    },
    {
      id: "pg-6",
      topic: "pg",
      prompt: "Ataque quantum dobra: 2, 4, 8, ... Qual o 4º termo?",
      options: ["10", "12", "16", "32"],
      correct: 2,
      formula: "aₙ = a₁ · qⁿ⁻¹",
      explanation: "q = 2; a₄ = 2·2³ = 16.",
    },
    {
      id: "pg-7",
      topic: "pg",
      prompt: "PG: 5, 10, 20, ... Qual o 4º termo?",
      options: ["30", "35", "40", "50"],
      correct: 2,
      formula: "aₙ = a₁ · qⁿ⁻¹",
      explanation: "q = 2; a₄ = 5·2³ = 40.",
    },
    {
      id: "pg-8",
      topic: "pg",
      prompt: "PG com a₁=1 e q=2. Qual é a₆?",
      options: ["16", "24", "32", "48"],
      correct: 2,
      formula: "aₙ = a₁ · qⁿ⁻¹",
      explanation: "a₆ = 1·2⁵ = 32.",
    },
  ],
};

export function drawQuestion(topic: Topic, exclude: string[] = []): Question {
  const pool = QUESTIONS[topic].filter((q) => !exclude.includes(q.id));
  const source = pool.length > 0 ? pool : QUESTIONS[topic];
  return source[Math.floor(Math.random() * source.length)];
}

export const FALLBACK_BOSS: import("./types").BossQuestion = {
  id: "boss-fallback",
  topic: "exp",
  source: "fallback",
  topics: ["exp", "log"],
  prompt: "DESAFIO FINAL — Some 2⁵ + log₂(16). Total?",
  options: ["30", "34", "36", "40"],
  correct: 2,
  formula: "2ˣ   ·   log_a(b) = x ⇔ aˣ = b",
  explanation: "2⁵ = 32 e log₂(16) = 4. Total = 32 + 4 = 36.",
};
