import type { Question, Topic } from "./types";

export const QUESTIONS: Record<Topic, Question[]> = {
  exp: [
    {
      id: "exp-1",
      topic: "exp",
      prompt:
        "O vírus REAPER dobra a cada turno: I(t) = 2ᵗ. Se I(4) = 16, quanto vale I(7)?",
      options: ["64", "96", "128", "256"],
      correct: 2,
      formula: "aˣ · aʸ = aˣ⁺ʸ",
      explanation: "2⁷ = 128. Cada turno dobra: 16 → 32 → 64 → 128.",
    },
    {
      id: "exp-2",
      topic: "exp",
      prompt: "Para neutralizar o patch você precisa calcular 3⁴ · 3². Qual o resultado?",
      options: ["243", "729", "81", "27"],
      correct: 1,
      formula: "aˣ · aʸ = aˣ⁺ʸ",
      explanation: "3⁴ · 3² = 3⁶ = 729 (soma os expoentes).",
    },
    {
      id: "exp-3",
      topic: "exp",
      prompt: "O servidor infecta com taxa f(x) = 2 · 5ˣ. Quanto vale f(3)?",
      options: ["125", "150", "250", "1000"],
      correct: 2,
      formula: "f(x) = a · bˣ",
      explanation: "2 · 5³ = 2 · 125 = 250.",
    },
    {
      id: "exp-4",
      topic: "exp",
      prompt: "Um patch cobre 2¹⁰ portas. Quantas portas é isso?",
      options: ["512", "1024", "2048", "256"],
      correct: 1,
      formula: "2¹⁰ = 1024",
      explanation: "2¹⁰ = 1024. Exatamente o limite de servidores do REAPER.",
    },
    {
      id: "exp-5",
      topic: "exp",
      prompt: "Se 2ˣ = 32, qual o valor de x?",
      options: ["4", "5", "6", "8"],
      correct: 1,
      formula: "aˣ = b  ⇔  x = log_a(b)",
      explanation: "2⁵ = 32, portanto x = 5.",
    },
    {
      id: "exp-6",
      topic: "exp",
      prompt: "Resolva: (2³)² · 2⁻¹",
      options: ["16", "32", "64", "128"],
      correct: 1,
      formula: "(aˣ)ʸ = aˣ·ʸ",
      explanation: "(2³)² = 2⁶; 2⁶ · 2⁻¹ = 2⁵ = 32.",
    },
    {
      id: "exp-7",
      topic: "exp",
      prompt: "I(t) = 2ᵗ. Quanto vale I(0) + I(3) + I(5)?",
      options: ["40", "41", "42", "44"],
      correct: 1,
      formula: "a⁰ = 1 (para a ≠ 0)",
      explanation: "1 + 8 + 32 = 41.",
    },
    {
      id: "exp-8",
      topic: "exp",
      prompt: "O firewall perde 2³ unidades por erro. Após 2 erros, quanto perdeu?",
      options: ["8", "12", "16", "24"],
      correct: 2,
      formula: "n · aˣ",
      explanation: "2³ = 8 por erro. 8 · 2 = 16.",
    },
  ],
  log: [
    {
      id: "log-1",
      topic: "log",
      prompt: "Quantos turnos até 1024? Calcule log₂(1024).",
      options: ["8", "9", "10", "12"],
      correct: 2,
      formula: "log_a(b) = x  ⇔  aˣ = b",
      explanation: "2¹⁰ = 1024, então log₂(1024) = 10.",
    },
    {
      id: "log-2",
      topic: "log",
      prompt: "Calcule log₂(512).",
      options: ["7", "8", "9", "10"],
      correct: 2,
      formula: "log_a(b) = x  ⇔  aˣ = b",
      explanation: "2⁹ = 512, logo log₂(512) = 9.",
    },
    {
      id: "log-3",
      topic: "log",
      prompt: "Quanto vale log₃(81)?",
      options: ["2", "3", "4", "5"],
      correct: 2,
      formula: "log_a(b) = x  ⇔  aˣ = b",
      explanation: "3⁴ = 81, portanto log₃(81) = 4.",
    },
    {
      id: "log-4",
      topic: "log",
      prompt: "Turno 4, infecção em 16. Quantos turnos até atingir 1024?",
      options: ["4", "5", "6", "8"],
      correct: 2,
      formula: "t = log₂(1024 / I)",
      explanation: "log₂(1024/16) = log₂(64) = 6. Faltam 6 turnos.",
    },
    {
      id: "log-5",
      topic: "log",
      prompt: "Simplifique: log₁₀(1000)",
      options: ["2", "3", "4", "10"],
      correct: 1,
      formula: "log_a(b) = x  ⇔  aˣ = b",
      explanation: "10³ = 1000, então log₁₀(1000) = 3.",
    },
    {
      id: "log-6",
      topic: "log",
      prompt: "log₂(8) + log₂(4) =",
      options: ["3", "5", "6", "12"],
      correct: 1,
      formula: "log(a) + log(b) = log(a · b)",
      explanation: "log₂(8) = 3 e log₂(4) = 2. Soma = 5.",
    },
    {
      id: "log-7",
      topic: "log",
      prompt: "Se log₅(x) = 3, então x vale:",
      options: ["15", "25", "125", "625"],
      correct: 2,
      formula: "log_a(b) = x  ⇔  aˣ = b",
      explanation: "5³ = 125.",
    },
    {
      id: "log-8",
      topic: "log",
      prompt: "log₂(256) − log₂(16) =",
      options: ["2", "4", "6", "8"],
      correct: 1,
      formula: "log(a) − log(b) = log(a / b)",
      explanation: "log₂(256) = 8, log₂(16) = 4. Diferença = 4.",
    },
  ],
  pa: [
    {
      id: "pa-1",
      topic: "pa",
      prompt: "Firewall começa em 10 e cresce +5 por turno. No turno 8 (a₈), quanto vale?",
      options: ["35", "40", "45", "50"],
      correct: 2,
      formula: "aₙ = a₁ + (n − 1) · r",
      explanation: "a₈ = 10 + 7·5 = 45.",
    },
    {
      id: "pa-2",
      topic: "pa",
      prompt: "PA com a₁ = 3, r = 4. Qual o 10º termo?",
      options: ["36", "39", "40", "43"],
      correct: 1,
      formula: "aₙ = a₁ + (n − 1) · r",
      explanation: "a₁₀ = 3 + 9·4 = 39.",
    },
    {
      id: "pa-3",
      topic: "pa",
      prompt: "Soma dos 10 primeiros termos de PA com a₁=2 e a₁₀=20:",
      options: ["100", "110", "120", "220"],
      correct: 1,
      formula: "Sₙ = (a₁ + aₙ) · n / 2",
      explanation: "S = (2+20)·10/2 = 110.",
    },
    {
      id: "pa-4",
      topic: "pa",
      prompt: "Em uma PA, a₃ = 7 e a₇ = 19. Qual a razão?",
      options: ["2", "3", "4", "6"],
      correct: 1,
      formula: "aₙ = aₖ + (n − k) · r",
      explanation: "19 = 7 + 4·r → r = 3.",
    },
    {
      id: "pa-5",
      topic: "pa",
      prompt: "PA: 5, 9, 13, 17, ... Qual o 6º termo?",
      options: ["21", "23", "25", "27"],
      correct: 2,
      formula: "aₙ = a₁ + (n − 1) · r",
      explanation: "r = 4; a₆ = 5 + 5·4 = 25.",
    },
    {
      id: "pa-6",
      topic: "pa",
      prompt: "Firewall no turno 12 com a₁=10 e r=5:",
      options: ["55", "60", "65", "70"],
      correct: 2,
      formula: "aₙ = a₁ + (n − 1) · r",
      explanation: "a₁₂ = 10 + 11·5 = 65.",
    },
    {
      id: "pa-7",
      topic: "pa",
      prompt: "Soma da PA: 2, 5, 8, 11, 14.",
      options: ["35", "40", "42", "45"],
      correct: 1,
      formula: "Sₙ = (a₁ + aₙ) · n / 2",
      explanation: "S = (2+14)·5/2 = 40.",
    },
    {
      id: "pa-8",
      topic: "pa",
      prompt: "PA tem a₁ = 100 e r = −7. Qual o 5º termo?",
      options: ["65", "72", "79", "86"],
      correct: 1,
      formula: "aₙ = a₁ + (n − 1) · r",
      explanation: "a₅ = 100 + 4·(−7) = 72.",
    },
  ],
  pg: [
    {
      id: "pg-1",
      topic: "pg",
      prompt: "Ataque QUANTUM dobra a cada acerto. a₁ = 2. Qual o 6º termo (a₆)?",
      options: ["32", "48", "64", "128"],
      correct: 2,
      formula: "aₙ = a₁ · qⁿ⁻¹",
      explanation: "a₆ = 2 · 2⁵ = 64.",
    },
    {
      id: "pg-2",
      topic: "pg",
      prompt: "PG: 3, 6, 12, 24, ... Qual o 7º termo?",
      options: ["96", "128", "192", "256"],
      correct: 2,
      formula: "aₙ = a₁ · qⁿ⁻¹",
      explanation: "q = 2; a₇ = 3 · 2⁶ = 192.",
    },
    {
      id: "pg-3",
      topic: "pg",
      prompt: "Soma dos 5 primeiros termos de PG com a₁=1 e q=2:",
      options: ["15", "31", "32", "63"],
      correct: 1,
      formula: "Sₙ = a₁ · (qⁿ − 1) / (q − 1)",
      explanation: "S = 1·(2⁵−1)/(2−1) = 31.",
    },
    {
      id: "pg-4",
      topic: "pg",
      prompt: "PG com a₁ = 5 e q = 3. Qual o 4º termo?",
      options: ["45", "75", "135", "405"],
      correct: 2,
      formula: "aₙ = a₁ · qⁿ⁻¹",
      explanation: "a₄ = 5 · 3³ = 5·27 = 135.",
    },
    {
      id: "pg-5",
      topic: "pg",
      prompt: "Qual a razão da PG: 64, 32, 16, 8, 4?",
      options: ["1/4", "1/2", "2", "4"],
      correct: 1,
      formula: "q = aₙ₊₁ / aₙ",
      explanation: "Cada termo é metade do anterior → q = 1/2.",
    },
    {
      id: "pg-6",
      topic: "pg",
      prompt: "Dano QUANTUM após 4 acertos seguidos (a₁=2, q=2):",
      options: ["8", "12", "16", "32"],
      correct: 2,
      formula: "aₙ = a₁ · qⁿ⁻¹",
      explanation: "a₄ = 2 · 2³ = 16.",
    },
    {
      id: "pg-7",
      topic: "pg",
      prompt: "Em uma PG, a₂ = 6 e a₅ = 162. Qual a razão?",
      options: ["2", "3", "4", "6"],
      correct: 1,
      formula: "aₙ = aₖ · qⁿ⁻ᵏ",
      explanation: "a₅/a₂ = q³ = 27, logo q = 3.",
    },
    {
      id: "pg-8",
      topic: "pg",
      prompt: "PG: 1, 2, 4, 8, 16, 32, 64. Qual o 8º termo?",
      options: ["96", "128", "192", "256"],
      correct: 1,
      formula: "aₙ = a₁ · qⁿ⁻¹",
      explanation: "a₈ = 1 · 2⁷ = 128.",
    },
  ],
};

export function drawQuestion(topic: Topic, exclude: string[] = []): Question {
  const pool = QUESTIONS[topic].filter((q) => !exclude.includes(q.id));
  const source = pool.length > 0 ? pool : QUESTIONS[topic];
  return source[Math.floor(Math.random() * source.length)];
}

export const FALLBACK_BOSS: import("./types").BossQuestion = {
  id: "boss-fallback",
  topic: "exp",
  source: "fallback",
  topics: ["pa", "log"],
  prompt:
    "PROTOCOLO FINAL — Some o 8º termo da PA (a₁=5, r=3) com log₂(64). Qual o valor total?",
  options: ["26", "30", "32", "38"],
  correct: 2,
  formula: "aₙ = a₁ + (n − 1) · r   ·   log_a(b) = x ⇔ aˣ = b",
  explanation: "a₈ = 5 + 7·3 = 26 e log₂(64) = 6. Total = 32.",
};
